# Generated by Django 4.2.5 on 2023-09-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="pen_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
