# Generated by Django 4.2.5 on 2023-09-17 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_author_pen_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinstance",
            old_name="imprint",
            new_name="publisher",
        ),
        migrations.AddField(
            model_name="bookinstance",
            name="date_published",
            field=models.DateField(default=datetime.date(2023, 9, 17)),
        ),
    ]
