# Generated by Django 4.2.5 on 2023-09-20 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_imprint_bookinstance_publisher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="date_published",
            field=models.DateField(default=datetime.date(2023, 9, 20)),
        ),
    ]
